# The configuration file for docking actions that robots can perform
# FleetName: The name of the fleet
#   DockName: The name of the docking waypoint
#     level_name: The level name
#     path: The waypoints that the robot will pass through during the docking process)
#     finish_waypoint: The name of the waypoint where the robot will end up at the end of the docking process


cleanerBotE:
  L2_zone_1:
    level_name: "L2"
    path: [ [19.92, -3.43, 6.0],
            [20.98, -3.24, 6.0],
            [22.32, -3.18, 6.0],
            [22.32, -4.30, 6.0],
            [21.11, -4.32, 0.0] ]
    finish_waypoint: "L2_zone_1"
  L2_zone_2:
    level_name: "L2"
    path: [ [6.16, -11.70, 6.0],
            [5.05, -10.19, 6.0],
            [5.10, -8.56, 6.0],
            [6.63, -8.35, 6.0],
            [5.20, -6.88, 6.0],
            [6.49, -6.99, 6.0],
            [6.63, -8.35, 3.14],
            [6.16, -11.70, 0.0]]
    finish_waypoint: "L2_zone_2"